name = "media-worker"
main = "src/index.ts"
compatibility_date = "2026-03-22"

[observability]
enabled = true

[cache]
enabled = true

[vars]
MEDIA_HOST = "https://static.letsboulder.com"

[env.staging]
name = "media-worker-staging"

[env.staging.vars]
MEDIA_HOST = "https://static.staging.letsboulder.com"
R2_ORIGIN_URL = "https://static.staging.letsboulder.com/origin"
R2_PRIVATE_BUCKET = "lb-staging-media-private"
R2_PUBLIC_BUCKET = "lb-staging-media-public"

[env.staging.triggers]
crons = ["*/2 * * * *"]

[[env.staging.queues.producers]]
binding = "MEDIA_QUEUE"
queue = "media-transform-queue-staging"

[[env.staging.queues.consumers]]
queue = "media-transform-queue-staging"
max_batch_size = 1

[[env.staging.r2_buckets]]
binding = "ORIGINALS_BUCKET"
bucket_name = "lb-staging-media-private"

[[env.staging.r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "lb-staging-media-public"

[env.staging.images]
binding = "IMAGES"

[[env.staging.routes]]
pattern = "static.staging.letsboulder.com"
custom_domain = true

[env.production]
name = "media-worker-production"

[env.production.vars]
MEDIA_HOST = "https://static.letsboulder.com"
R2_ORIGIN_URL = "https://r2-origin-prod.letsboulder.com"
SUPABASE_URL = "https://glxnbxbkedeogtcivpsx.supabase.co"
R2_PRIVATE_BUCKET = "lb-prod-media-private"
R2_PUBLIC_BUCKET = "lb-prod-media-public"

[env.production.triggers]
crons = ["*/2 * * * *"]

[[env.production.routes]]
pattern = "static.letsboulder.com/*"
zone_name = "letsboulder.com"

[[env.production.r2_buckets]]
binding = "ORIGINALS_BUCKET"
bucket_name = "lb-prod-media-private"

[[env.production.r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "lb-prod-media-public"

[env.production.images]
binding = "IMAGES"

[[env.production.queues.producers]]
binding = "MEDIA_QUEUE"
queue = "media-transform-queue-prod"

[[env.production.queues.consumers]]
queue = "media-transform-queue-prod"
max_batch_size = 1
