-- Auto-generated migration: Gold Standard Geography
-- Simplified version - adds countries without schema restructure

-- 0. Drop old regions table (replaced by new geography schema)
DROP TABLE IF EXISTS public.regions CASCADE;

-- 1. Create countries table (with boundary column for future Natural Earth data)
CREATE TABLE IF NOT EXISTS public.countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  iso_a2 TEXT NOT NULL UNIQUE,
  iso_a3 TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  name_long TEXT,
  formal_name TEXT,
  abbrev TEXT,
  admin_type TEXT,
  region_id UUID,
  scale_rank INTEGER,
  label_rank INTEGER,
  map_color INTEGER,
  boundary geometry(Geometry, 4326),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create continents table
CREATE TABLE IF NOT EXISTS public.continents (
  name TEXT PRIMARY KEY
);

-- 3. Create un_regions table  
CREATE TABLE IF NOT EXISTS public.un_regions (
  name TEXT PRIMARY KEY,
  continent_name TEXT NOT NULL REFERENCES public.continents(name)
);

-- 4. Create regions table (subregions)
CREATE TABLE IF NOT EXISTS public.regions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  un_region_name TEXT NOT NULL REFERENCES public.un_regions(name),
  country_code VARCHAR(2),
  center_lat NUMERIC(10,8),
  center_lon NUMERIC(11,8),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Add country_id to existing tables
ALTER TABLE public.crags ADD COLUMN IF NOT EXISTS country_id UUID REFERENCES public.countries(id) ON DELETE SET NULL;
ALTER TABLE public.places ADD COLUMN IF NOT EXISTS country_id UUID REFERENCES public.countries(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_crags_country_id ON public.crags(country_id);
CREATE INDEX IF NOT EXISTS idx_places_country_id ON public.places(country_id);

-- 6. Insert continents
INSERT INTO public.continents (name) VALUES
  ('Africa'),
  ('Americas'),
  ('Antarctica'),
  ('Asia'),
  ('Europe'),
  ('Oceania'),
  ('Seven seas (open ocean)')
ON CONFLICT (name) DO NOTHING;

-- 7. Insert UN regions
INSERT INTO public.un_regions (name, continent_name) VALUES
  ('Africa', 'Africa'),
  ('Americas', 'Americas'),
  ('Antarctica', 'Antarctica'),
  ('Asia', 'Asia'),
  ('Europe', 'Europe'),
  ('Oceania', 'Oceania'),
  ('Seven seas (open ocean)', 'Seven seas (open ocean)')
ON CONFLICT (name) DO UPDATE SET continent_name = EXCLUDED.continent_name;

-- 8. Insert regions (subregions)
INSERT INTO public.regions (name, un_region_name) VALUES
  ('Antarctica', 'Antarctica'),
  ('Australia and New Zealand', 'Oceania'),
  ('Caribbean', 'Americas'),
  ('Central America', 'Americas'),
  ('Central Asia', 'Asia'),
  ('Eastern Africa', 'Africa'),
  ('Eastern Asia', 'Asia'),
  ('Eastern Europe', 'Europe'),
  ('Melanesia', 'Oceania'),
  ('Middle Africa', 'Africa'),
  ('Northern Africa', 'Africa'),
  ('Northern America', 'Americas'),
  ('Northern Europe', 'Europe'),
  ('Seven seas (open ocean)', 'Seven seas (open ocean)'),
  ('South America', 'Americas'),
  ('South-Eastern Asia', 'Asia'),
  ('Southern Africa', 'Africa'),
  ('Southern Asia', 'Asia'),
  ('Southern Europe', 'Europe'),
  ('Western Africa', 'Africa'),
  ('Western Asia', 'Asia'),
  ('Western Europe', 'Europe')
ON CONFLICT (name) DO UPDATE SET un_region_name = EXCLUDED.un_region_name;

-- 9. Insert countries
INSERT INTO public.countries (iso_a2, iso_a3, name, name_long, formal_name, abbrev, admin_type, region_id, scale_rank, label_rank, map_color) VALUES
  ('AF', 'AFG', 'Afghanistan', 'Afghanistan', 'Islamic State of Afghanistan', 'Afg.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 3, 5),
  ('AO', 'AGO', 'Angola', 'Angola', 'People''s Republic of Angola', 'Ang.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 3, 3),
  ('AL', 'ALB', 'Albania', 'Albania', 'Republic of Albania', 'Alb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 6, 1),
  ('AE', 'ARE', 'United Arab Emirates', 'United Arab Emirates', 'United Arab Emirates', 'U.A.E.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 4, 2),
  ('AR', 'ARG', 'Argentina', 'Argentina', 'Argentine Republic', 'Arg.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 2, 3),
  ('AM', 'ARM', 'Armenia', 'Armenia', 'Republic of Armenia', 'Arm.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 6, 3),
  ('AQ', 'ATA', 'Antarctica', 'Antarctica', '', 'Ant.', 'Indeterminate', (SELECT id FROM public.regions WHERE name = 'Antarctica' LIMIT 1), 1, 4, 4),
  ('TF', 'ATF', 'Fr. S. Antarctic Lands', 'French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', 'Fr. S.A.L.', 'Dependency', (SELECT id FROM public.regions WHERE name = 'Seven seas (open ocean)' LIMIT 1), 3, 6, 7),
  ('AU', 'AUS', 'Australia', 'Australia', 'Commonwealth of Australia', 'Auz.', 'Country', (SELECT id FROM public.regions WHERE name = 'Australia and New Zealand' LIMIT 1), 1, 2, 1),
  ('AT', 'AUT', 'Austria', 'Austria', 'Republic of Austria', 'Aust.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 4, 3),
  ('AZ', 'AZE', 'Azerbaijan', 'Azerbaijan', 'Republic of Azerbaijan', 'Aze.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 1),
  ('BI', 'BDI', 'Burundi', 'Burundi', 'Republic of Burundi', 'Bur.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 6, 2),
  ('BE', 'BEL', 'Belgium', 'Belgium', 'Kingdom of Belgium', 'Belg.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 2, 3),
  ('BJ', 'BEN', 'Benin', 'Benin', 'Republic of Benin', 'Benin', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 5, 1),
  ('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'B.F.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 2),
  ('BD', 'BGD', 'Bangladesh', 'Bangladesh', 'People''s Republic of Bangladesh', 'Bang.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 3, 3),
  ('BG', 'BGR', 'Bulgaria', 'Bulgaria', 'Republic of Bulgaria', 'Bulg.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 4, 4),
  ('BS', 'BHS', 'Bahamas', 'Bahamas', 'Commonwealth of the Bahamas', 'Bhs.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 4, 1),
  ('BA', 'BIH', 'Bosnia and Herz.', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'B.H.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 5, 1),
  ('BY', 'BLR', 'Belarus', 'Belarus', 'Republic of Belarus', 'Bela.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 4, 1),
  ('BZ', 'BLZ', 'Belize', 'Belize', 'Belize', 'Belize', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 6, 1),
  ('BO', 'BOL', 'Bolivia', 'Bolivia', 'Plurinational State of Bolivia', 'Bolivia', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 3, 1),
  ('BR', 'BRA', 'Brazil', 'Brazil', 'Federative Republic of Brazil', 'Brazil', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 2, 5),
  ('BN', 'BRN', 'Brunei', 'Brunei Darussalam', 'Negara Brunei Darussalam', 'Brunei', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 6, 4),
  ('BT', 'BTN', 'Bhutan', 'Bhutan', 'Kingdom of Bhutan', 'Bhutan', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 5, 5),
  ('BW', 'BWA', 'Botswana', 'Botswana', 'Republic of Botswana', 'Bwa.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Africa' LIMIT 1), 1, 4, 6),
  ('CF', 'CAF', 'Central African Rep.', 'Central African Republic', 'Central African Republic', 'C.A.R.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 4, 5),
  ('CA', 'CAN', 'Canada', 'Canada', 'Canada', 'Can.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern America' LIMIT 1), 1, 2, 6),
  ('CH', 'CHE', 'Switzerland', 'Switzerland', 'Swiss Confederation', 'Switz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 4, 5),
  ('CL', 'CHL', 'Chile', 'Chile', 'Republic of Chile', 'Chile', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 2, 5),
  ('CN', 'CHN', 'China', 'China', 'People''s Republic of China', 'China', 'Country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 2, 4),
  ('CI', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire', 'Republic of Ivory Coast', 'I.C.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 4),
  ('CM', 'CMR', 'Cameroon', 'Cameroon', 'Republic of Cameroon', 'Cam.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 3, 1),
  ('CD', 'COD', 'Dem. Rep. Congo', 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'D.R.C.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 2, 4),
  ('CG', 'COG', 'Congo', 'Republic of Congo', 'Republic of Congo', 'Rep. Congo', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 4, 2),
  ('CO', 'COL', 'Colombia', 'Colombia', 'Republic of Colombia', 'Col.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 2, 2),
  ('CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Republic of Costa Rica', 'C.R.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 5, 3),
  ('CU', 'CUB', 'Cuba', 'Cuba', 'Republic of Cuba', 'Cuba', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 3, 3),
  ('CY', 'CYP', 'Cyprus', 'Cyprus', 'Republic of Cyprus', 'Cyp.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 1),
  ('CZ', 'CZE', 'Czech Rep.', 'Czech Republic', 'Czech Republic', 'Cz. Rep.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 5, 1),
  ('DE', 'DEU', 'Germany', 'Germany', 'Federal Republic of Germany', 'Ger.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 2, 2),
  ('DJ', 'DJI', 'Djibouti', 'Djibouti', 'Republic of Djibouti', 'Dji.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 5, 1),
  ('DK', 'DNK', 'Denmark', 'Denmark', 'Kingdom of Denmark', 'Den.', 'Country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 4, 4),
  ('DO', 'DOM', 'Dominican Rep.', 'Dominican Republic', 'Dominican Republic', 'Dom. Rep.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 5, 5),
  ('DZ', 'DZA', 'Algeria', 'Algeria', 'People''s Democratic Republic of Algeria', 'Alg.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 3, 5),
  ('EC', 'ECU', 'Ecuador', 'Ecuador', 'Republic of Ecuador', 'Ecu.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 3, 1),
  ('EG', 'EGY', 'Egypt', 'Egypt', 'Arab Republic of Egypt', 'Egypt', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 2, 4),
  ('ER', 'ERI', 'Eritrea', 'Eritrea', 'State of Eritrea', 'Erit.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 4, 3),
  ('ES', 'ESP', 'Spain', 'Spain', 'Kingdom of Spain', 'Sp.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 2, 4),
  ('EE', 'EST', 'Estonia', 'Estonia', 'Republic of Estonia', 'Est.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 6, 3),
  ('ET', 'ETH', 'Ethiopia', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Eth.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 2, 4),
  ('FI', 'FIN', 'Finland', 'Finland', 'Republic of Finland', 'Fin.', 'Country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 3, 4),
  ('FJ', 'FJI', 'Fiji', 'Fiji', 'Republic of Fiji', 'Fiji', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Melanesia' LIMIT 1), 1, 6, 5),
  ('FK', 'FLK', 'Falkland Is.', 'Falkland Islands', 'Falkland Islands', 'Flk. Is.', 'Dependency', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 5, 6),
  ('FR', 'FRA', 'France', 'France', 'French Republic', 'Fr.', 'Country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 2, 7),
  ('GA', 'GAB', 'Gabon', 'Gabon', 'Gabonese Republic', 'Gabon', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 4, 6),
  ('GB', 'GBR', 'United Kingdom', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'U.K.', 'Country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 2, 6),
  ('GE', 'GEO', 'Georgia', 'Georgia', 'Georgia', 'Geo.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 5),
  ('GH', 'GHA', 'Ghana', 'Ghana', 'Republic of Ghana', 'Ghana', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 5),
  ('GN', 'GIN', 'Guinea', 'Guinea', 'Republic of Guinea', 'Gin.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 6),
  ('GM', 'GMB', 'Gambia', 'The Gambia', 'Republic of the Gambia', 'Gambia', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 6, 1),
  ('GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'GnB.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 6, 3),
  ('GQ', 'GNQ', 'Eq. Guinea', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'Eq. G.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 4, 4),
  ('GR', 'GRC', 'Greece', 'Greece', 'Hellenic Republic', 'Greece', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 3, 2),
  ('GL', 'GRL', 'Greenland', 'Greenland', 'Greenland', 'Grlnd.', 'Country', (SELECT id FROM public.regions WHERE name = 'Northern America' LIMIT 1), 1, 3, 4),
  ('GT', 'GTM', 'Guatemala', 'Guatemala', 'Republic of Guatemala', 'Guat.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 3, 3),
  ('GY', 'GUY', 'Guyana', 'Guyana', 'Co-operative Republic of Guyana', 'Guy.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 4, 3),
  ('HN', 'HND', 'Honduras', 'Honduras', 'Republic of Honduras', 'Hond.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 5, 2),
  ('HR', 'HRV', 'Croatia', 'Croatia', 'Republic of Croatia', 'Cro.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 6, 5),
  ('HT', 'HTI', 'Haiti', 'Haiti', 'Republic of Haiti', 'Haiti', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 5, 2),
  ('HU', 'HUN', 'Hungary', 'Hungary', 'Republic of Hungary', 'Hun.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 5, 4),
  ('ID', 'IDN', 'Indonesia', 'Indonesia', 'Republic of Indonesia', 'Indo.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 2, 6),
  ('IN', 'IND', 'India', 'India', 'Republic of India', 'India', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 2, 1),
  ('IE', 'IRL', 'Ireland', 'Ireland', 'Ireland', 'Ire.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 3, 2),
  ('IR', 'IRN', 'Iran', 'Iran', 'Islamic Republic of Iran', 'Iran', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 2, 4),
  ('IQ', 'IRQ', 'Iraq', 'Iraq', 'Republic of Iraq', 'Iraq', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 3, 1),
  ('IS', 'ISL', 'Iceland', 'Iceland', 'Republic of Iceland', 'Iceland', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 3, 1),
  ('IL', 'ISR', 'Israel', 'Israel', 'State of Israel', 'Isr.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 4, 3),
  ('IT', 'ITA', 'Italy', 'Italy', 'Italian Republic', 'Italy', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 2, 6),
  ('JM', 'JAM', 'Jamaica', 'Jamaica', 'Jamaica', 'Jam.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 4, 1),
  ('JO', 'JOR', 'Jordan', 'Jordan', 'Hashemite Kingdom of Jordan', 'Jord.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 4, 5),
  ('JP', 'JPN', 'Japan', 'Japan', 'Japan', 'Japan', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 2, 5),
  ('KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan', 'Republic of Kazakhstan', 'Kaz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central Asia' LIMIT 1), 1, 3, 6),
  ('KE', 'KEN', 'Kenya', 'Kenya', 'Republic of Kenya', 'Ken.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 2, 5),
  ('KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstan', 'Kyrgyz Republic', 'Kgz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central Asia' LIMIT 1), 1, 4, 5),
  ('KH', 'KHM', 'Cambodia', 'Cambodia', 'Kingdom of Cambodia', 'Camb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 3, 6),
  ('KR', 'KOR', 'Korea', 'Republic of Korea', 'Republic of Korea', 'S.K.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 2, 4),
  ('KW', 'KWT', 'Kuwait', 'Kuwait', 'State of Kuwait', 'Kwt.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 6, 2),
  ('LA', 'LAO', 'Lao PDR', 'Lao PDR', 'Lao People''s Democratic Republic', 'Laos', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 4, 1),
  ('LB', 'LBN', 'Lebanon', 'Lebanon', 'Lebanese Republic', 'Leb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 4),
  ('LR', 'LBR', 'Liberia', 'Liberia', 'Republic of Liberia', 'Liberia', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 4, 2),
  ('LY', 'LBY', 'Libya', 'Libya', 'Libya', 'Libya', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 3, 1),
  ('LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Sri L.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 3, 3),
  ('LS', 'LSO', 'Lesotho', 'Lesotho', 'Kingdom of Lesotho', 'Les.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Africa' LIMIT 1), 1, 6, 1),
  ('LT', 'LTU', 'Lithuania', 'Lithuania', 'Republic of Lithuania', 'Lith.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 5, 6),
  ('LU', 'LUX', 'Luxembourg', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Lux.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 6, 1),
  ('LV', 'LVA', 'Latvia', 'Latvia', 'Republic of Latvia', 'Lat.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 5, 4),
  ('MA', 'MAR', 'Morocco', 'Morocco', 'Kingdom of Morocco', 'Mor.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 3, 2),
  ('MD', 'MDA', 'Moldova', 'Moldova', 'Republic of Moldova', 'Mda.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 6, 3),
  ('MG', 'MDG', 'Madagascar', 'Madagascar', 'Republic of Madagascar', 'Mad.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 6),
  ('MX', 'MEX', 'Mexico', 'Mexico', 'United Mexican States', 'Mex.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 2, 6),
  ('MK', 'MKD', 'Macedonia', 'Macedonia', 'Former Yugoslav Republic of Macedonia', 'Mkd.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 6, 5),
  ('ML', 'MLI', 'Mali', 'Mali', 'Republic of Mali', 'Mali', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 1),
  ('MM', 'MMR', 'Myanmar', 'Myanmar', 'Republic of the Union of Myanmar', 'Myan.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 3, 2),
  ('ME', 'MNE', 'Montenegro', 'Montenegro', 'Montenegro', 'Mont.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 6, 4),
  ('MN', 'MNG', 'Mongolia', 'Mongolia', 'Mongolia', 'Mong.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 3, 3),
  ('MZ', 'MOZ', 'Mozambique', 'Mozambique', 'Republic of Mozambique', 'Moz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 4),
  ('MR', 'MRT', 'Mauritania', 'Mauritania', 'Islamic Republic of Mauritania', 'Mrt.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 3),
  ('MW', 'MWI', 'Malawi', 'Malawi', 'Republic of Malawi', 'Mal.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 6, 1),
  ('MY', 'MYS', 'Malaysia', 'Malaysia', 'Malaysia', 'Malay.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 3, 2),
  ('NA', 'NAM', 'Namibia', 'Namibia', 'Republic of Namibia', 'Nam.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Africa' LIMIT 1), 1, 3, 4),
  ('NC', 'NCL', 'New Caledonia', 'New Caledonia', 'New Caledonia', 'New C.', 'Dependency', (SELECT id FROM public.regions WHERE name = 'Melanesia' LIMIT 1), 1, 3, 7),
  ('NE', 'NER', 'Niger', 'Niger', 'Republic of Niger', 'Niger', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 4),
  ('NG', 'NGA', 'Nigeria', 'Nigeria', 'Federal Republic of Nigeria', 'Nigeria', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 2, 3),
  ('NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Republic of Nicaragua', 'Nic.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 5, 1),
  ('NL', 'NLD', 'Netherlands', 'Netherlands', 'Kingdom of the Netherlands', 'Neth.', 'Country', (SELECT id FROM public.regions WHERE name = 'Western Europe' LIMIT 1), 1, 5, 4),
  ('NO', 'NOR', 'Norway', 'Norway', 'Kingdom of Norway', 'Nor.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 3, 5),
  ('NP', 'NPL', 'Nepal', 'Nepal', 'Nepal', 'Nepal', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 3, 2),
  ('NZ', 'NZL', 'New Zealand', 'New Zealand', 'New Zealand', 'N.Z.', 'Country', (SELECT id FROM public.regions WHERE name = 'Australia and New Zealand' LIMIT 1), 1, 2, 3),
  ('OM', 'OMN', 'Oman', 'Oman', 'Sultanate of Oman', 'Oman', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 4, 1),
  ('PK', 'PAK', 'Pakistan', 'Pakistan', 'Islamic Republic of Pakistan', 'Pak.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Asia' LIMIT 1), 1, 2, 2),
  ('PA', 'PAN', 'Panama', 'Panama', 'Republic of Panama', 'Pan.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 4, 4),
  ('PE', 'PER', 'Peru', 'Peru', 'Republic of Peru', 'Peru', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 2, 4),
  ('PH', 'PHL', 'Philippines', 'Philippines', 'Republic of the Philippines', 'Phil.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 2, 3),
  ('PG', 'PNG', 'Papua New Guinea', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'P.N.G.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Melanesia' LIMIT 1), 1, 2, 4),
  ('PL', 'POL', 'Poland', 'Poland', 'Republic of Poland', 'Pol.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 3, 3),
  ('PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'P.R.', 'Dependency', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 5, 4),
  ('KP', 'PRK', 'Dem. Rep. Korea', 'Dem. Rep. Korea', 'Democratic People''s Republic of Korea', 'N.K.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 3, 3),
  ('PT', 'PRT', 'Portugal', 'Portugal', 'Portuguese Republic', 'Port.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 2, 1),
  ('PY', 'PRY', 'Paraguay', 'Paraguay', 'Republic of Paraguay', 'Para.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 4, 6),
  ('PS', 'PSE', 'Palestine', 'Palestine', 'West Bank and Gaza', 'Pal.', 'Disputed', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 3),
  ('QA', 'QAT', 'Qatar', 'Qatar', 'State of Qatar', 'Qatar', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 5, 3),
  ('RO', 'ROU', 'Romania', 'Romania', 'Romania', 'Rom.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 3, 1),
  ('RU', 'RUS', 'Russia', 'Russian Federation', 'Russian Federation', 'Rus.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 2, 2),
  ('RW', 'RWA', 'Rwanda', 'Rwanda', 'Republic of Rwanda', 'Rwa.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 5),
  ('EH', 'ESH', 'W. Sahara', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'W. Sah.', 'Indeterminate', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 7, 4),
  ('SA', 'SAU', 'Saudi Arabia', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'Saud.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 2, 6),
  ('SD', 'SDN', 'Sudan', 'Sudan', 'Republic of the Sudan', 'Sudan', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 3, 2),
  ('SS', 'SSD', 'S. Sudan', 'South Sudan', 'Republic of South Sudan', 'S. Sud.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 1),
  ('SN', 'SEN', 'Senegal', 'Senegal', 'Republic of Senegal', 'Sen.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 3, 2),
  ('SB', 'SLB', 'Solomon Is.', 'Solomon Islands', '', 'S. Is.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Melanesia' LIMIT 1), 1, 3, 1),
  ('SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Republic of Sierra Leone', 'S.L.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 4, 1),
  ('SV', 'SLV', 'El Salvador', 'El Salvador', 'Republic of El Salvador', 'El. S.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central America' LIMIT 1), 1, 6, 1),
  ('SO', 'SOM', 'Somalia', 'Somalia', 'Federal Republic of Somalia', 'Som.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 6, 2),
  ('RS', 'SRB', 'Serbia', 'Serbia', 'Republic of Serbia', 'Serb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 5, 3),
  ('SR', 'SUR', 'Suriname', 'Suriname', 'Republic of Suriname', 'Sur.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 4, 1),
  ('SK', 'SVK', 'Slovakia', 'Slovakia', 'Slovak Republic', 'Svk.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 6, 2),
  ('SI', 'SVN', 'Slovenia', 'Slovenia', 'Republic of Slovenia', 'Slo.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Europe' LIMIT 1), 1, 6, 2),
  ('SE', 'SWE', 'Sweden', 'Sweden', 'Kingdom of Sweden', 'Swe.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Europe' LIMIT 1), 1, 3, 1),
  ('SZ', 'SWZ', 'Swaziland', 'Swaziland', 'Kingdom of Swaziland', 'Swz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Africa' LIMIT 1), 1, 4, 3),
  ('SY', 'SYR', 'Syria', 'Syria', 'Syrian Arab Republic', 'Syria', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 3, 2),
  ('TD', 'TCD', 'Chad', 'Chad', 'Republic of Chad', 'Chad', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Middle Africa' LIMIT 1), 1, 3, 6),
  ('TG', 'TGO', 'Togo', 'Togo', 'Togolese Republic', 'Togo', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Africa' LIMIT 1), 1, 6, 3),
  ('TH', 'THA', 'Thailand', 'Thailand', 'Kingdom of Thailand', 'Thai.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 3, 3),
  ('TJ', 'TJK', 'Tajikistan', 'Tajikistan', 'Republic of Tajikistan', 'Tjk.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central Asia' LIMIT 1), 1, 4, 3),
  ('TM', 'TKM', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', 'Turkm.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central Asia' LIMIT 1), 1, 4, 3),
  ('TL', 'TLS', 'Timor-Leste', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'T.L.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 5, 2),
  ('TT', 'TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Tr.T.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Caribbean' LIMIT 1), 1, 5, 5),
  ('TN', 'TUN', 'Tunisia', 'Tunisia', 'Republic of Tunisia', 'Tun.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Northern Africa' LIMIT 1), 1, 3, 4),
  ('TR', 'TUR', 'Turkey', 'Turkey', 'Republic of Turkey', 'Tur.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 2, 6),
  ('TW', 'TWN', 'Taiwan', 'Taiwan', '', 'Taiwan', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Asia' LIMIT 1), 1, 3, 1),
  ('TZ', 'TZA', 'Tanzania', 'Tanzania', 'United Republic of Tanzania', 'Tanz.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 3),
  ('UG', 'UGA', 'Uganda', 'Uganda', 'Republic of Uganda', 'Uga.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 6),
  ('UA', 'UKR', 'Ukraine', 'Ukraine', 'Ukraine', 'Ukr.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Europe' LIMIT 1), 1, 3, 5),
  ('UY', 'URY', 'Uruguay', 'Uruguay', 'Oriental Republic of Uruguay', 'Ury.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 4, 1),
  ('US', 'USA', 'United States', 'United States', 'United States of America', 'U.S.A.', 'Country', (SELECT id FROM public.regions WHERE name = 'Northern America' LIMIT 1), 1, 2, 4),
  ('UZ', 'UZB', 'Uzbekistan', 'Uzbekistan', 'Republic of Uzbekistan', 'Uzb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Central Asia' LIMIT 1), 1, 3, 2),
  ('VE', 'VEN', 'Venezuela', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Ven.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South America' LIMIT 1), 1, 3, 1),
  ('VN', 'VNM', 'Vietnam', 'Vietnam', 'Socialist Republic of Vietnam', 'Viet.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'South-Eastern Asia' LIMIT 1), 1, 2, 5),
  ('VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Republic of Vanuatu', 'Van.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Melanesia' LIMIT 1), 1, 4, 6),
  ('YE', 'YEM', 'Yemen', 'Yemen', 'Republic of Yemen', 'Yem.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Western Asia' LIMIT 1), 1, 3, 5),
  ('ZA', 'ZAF', 'South Africa', 'South Africa', 'Republic of South Africa', 'S.Af.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Southern Africa' LIMIT 1), 1, 2, 2),
  ('ZM', 'ZMB', 'Zambia', 'Zambia', 'Republic of Zambia', 'Zambia', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 5),
  ('ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'Republic of Zimbabwe', 'Zimb.', 'Sovereign country', (SELECT id FROM public.regions WHERE name = 'Eastern Africa' LIMIT 1), 1, 3, 1)
ON CONFLICT (iso_a2) DO UPDATE SET
  iso_a3 = EXCLUDED.iso_a3,
  name = EXCLUDED.name,
  name_long = EXCLUDED.name_long,
  formal_name = EXCLUDED.formal_name,
  abbrev = EXCLUDED.abbrev,
  admin_type = EXCLUDED.admin_type,
  region_id = EXCLUDED.region_id,
  scale_rank = EXCLUDED.scale_rank,
  label_rank = EXCLUDED.label_rank,
  map_color = EXCLUDED.map_color;
