-- letsboulder: evidence-based schema audit, 2026-09-07.
-- Migration filename generated by the pinned CLI in CI run 34205742649.
-- Apply through staging, then the main production workflow. Never run through MCP.
-- Baseline inspected: both projects through 20260830143000; app main 778e8213.
-- Forward-only and repeatable. No tables, columns, route geometry, or logs are deleted.
-- Data corrections: orphan creator UUIDs become NULL; derived vote summaries are rebuilt.
-- Ordinary index builds suit the audited ~10.6 MiB application schema. They block
-- writes while building. Reassess size/locking if deployment is substantially delayed.
-- This transaction fails rather than waiting indefinitely for conflicting locks.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
SET LOCAL search_path = public, pg_catalog;

-- 1. Remove table-wide privileges that client API roles do not need.
-- RLS does not protect TRUNCATE/REFERENCES. MAINTAIN is also unnecessary on PG17.
REVOKE TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON ALL TABLES IN SCHEMA public
  FROM PUBLIC, anon, authenticated;
-- Existing postgres defaults already deny client access; make that contract explicit.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;
-- Managed supabase_admin defaults are intentionally outside this migration's scope.

-- Reconcile staging-only DML grants with the production contract; preserve column grants.

REVOKE DELETE, INSERT, UPDATE ON TABLE public."admin_actions" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."climb_corrections" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."climb_verifications" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."climb_video_betas" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."climbs" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."comments" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."community_place_follows" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."community_post_comments" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."community_posts" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."correction_votes" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."crags" FROM "anon";

REVOKE DELETE, INSERT, SELECT, UPDATE ON TABLE public."deleted_accounts" FROM "anon";

REVOKE DELETE, INSERT, SELECT, UPDATE ON TABLE public."deleted_accounts" FROM "authenticated";

REVOKE DELETE, INSERT, SELECT, UPDATE ON TABLE public."deletion_requests" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."grade_votes" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."grades" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."images" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."notifications" FROM "anon";

REVOKE INSERT ON TABLE public."notifications" FROM "authenticated";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."places" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."product_clicks" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."product_clicks" FROM "authenticated";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."route_grades" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."route_lines" FROM "anon";

REVOKE DELETE, INSERT, UPDATE ON TABLE public."user_climbs" FROM "anon";

-- 2. Missing FK indexes: 56 observed gaps plus the new crag editor FK.
-- A different valid full B-tree with the same leading key already covers a FK.
-- Do not duplicate that index. Fail on a conflicting requested name instead of
-- silently treating IF NOT EXISTS as proof of the index definition.
DO $indexes$
DECLARE r record; table_oid oid; key_numbers smallint[]; named_oid oid;
BEGIN
  FOR r IN SELECT * FROM (VALUES

('climbs', ARRAY['sector_id']::text[], 'climbs_sector_id_idx'),
    ('contribution_bounties', ARRAY['completed_by_user_id']::text[], 'contribution_bounties_completed_by_user_id_idx'),
    ('contribution_bounties', ARRAY['completed_event_id']::text[], 'contribution_bounties_completed_event_id_idx'),
    ('contribution_bounties', ARRAY['crag_id']::text[], 'contribution_bounties_crag_id_idx'),
    ('contribution_bounties', ARRAY['created_by_event_id']::text[], 'contribution_bounties_created_by_event_id_idx'),
    ('contribution_bounties', ARRAY['place_id']::text[], 'contribution_bounties_place_id_idx'),
    ('contribution_events', ARRAY['climb_id']::text[], 'contribution_events_climb_id_idx'),
    ('contribution_events', ARRAY['crag_id']::text[], 'contribution_events_crag_id_idx'),
    ('contribution_events', ARRAY['image_id']::text[], 'contribution_events_image_id_idx'),
    ('countries', ARRAY['region_id']::text[], 'countries_region_id_idx'),
    ('crag_images', ARRAY['sector_id']::text[], 'crag_images_sector_id_idx'),
    ('crag_maintainers', ARRAY['assigned_by']::text[], 'crag_maintainers_assigned_by_idx'),
    ('crag_maintainers', ARRAY['user_id']::text[], 'crag_maintainers_user_id_idx'),
    ('crag_metadata_proposals', ARRAY['approved_commit_id']::text[], 'crag_metadata_proposals_approved_commit_id_idx'),
    ('crag_metadata_proposals', ARRAY['base_revision_id']::text[], 'crag_metadata_proposals_base_revision_id_idx'),
    ('crag_metadata_proposals', ARRAY['reviewer_id']::text[], 'crag_metadata_proposals_reviewer_id_idx'),
    ('crag_metadata_proposals', ARRAY['source_image_id']::text[], 'crag_metadata_proposals_source_image_id_idx'),
    ('crag_publication_events', ARRAY['changed_by']::text[], 'crag_publication_events_changed_by_idx'),
    ('crag_reports', ARRAY['moderator_id']::text[], 'crag_reports_moderator_id_idx'),
    ('crags', ARRAY['created_by']::text[], 'crags_created_by_idx'),
    ('crags', ARRAY['published_by']::text[], 'crags_published_by_idx'),
    ('crags', ARRAY['reviewed_by']::text[], 'crags_reviewed_by_idx'),
    ('deletion_requests', ARRAY['user_id']::text[], 'deletion_requests_user_id_idx'),
    ('images', ARRAY['last_edited_by']::text[], 'images_last_edited_by_idx'),
    ('images', ARRAY['upload_crag_id']::text[], 'images_upload_crag_id_idx'),
    ('images', ARRAY['upload_draft_id']::text[], 'images_upload_draft_id_idx'),
    ('media_deletion_jobs', ARRAY['replay_of_job_id']::text[], 'media_deletion_jobs_replay_of_job_id_idx'),
    ('media_jobs', ARRAY['replay_of_job_id']::text[], 'media_jobs_replay_of_job_id_idx'),
    ('regions', ARRAY['un_region_name']::text[], 'regions_un_region_name_idx'),
    ('saved_climbs', ARRAY['climb_id']::text[], 'saved_climbs_climb_id_idx'),
    ('saved_crags', ARRAY['crag_id']::text[], 'saved_crags_crag_id_idx'),
    ('sectors', ARRAY['crag_id']::text[], 'sectors_crag_id_idx'),
    ('submission_collaborator_invites', ARRAY['created_by']::text[], 'submission_collaborator_invites_created_by_idx'),
    ('submission_collaborators', ARRAY['created_by']::text[], 'submission_collaborators_created_by_idx'),
    ('submission_draft_collaborator_invites', ARRAY['created_by']::text[], 'submission_draft_collaborator_invites_created_by_idx'),
    ('submission_draft_collaborators', ARRAY['created_by']::text[], 'submission_draft_collaborators_created_by_idx'),
    ('submission_draft_images', ARRAY['linked_crag_image_id']::text[], 'submission_draft_images_linked_crag_image_id_idx'),
    ('submission_draft_images', ARRAY['linked_image_id']::text[], 'submission_draft_images_linked_image_id_idx'),
    ('submission_draft_routes', ARRAY['created_by']::text[], 'submission_draft_routes_created_by_idx'),
    ('submission_draft_routes', ARRAY['updated_by']::text[], 'submission_draft_routes_updated_by_idx'),
    ('submission_drafts', ARRAY['last_edited_by']::text[], 'submission_drafts_last_edited_by_idx'),
    ('topo_replacement_routes', ARRAY['climb_id']::text[], 'topo_replacement_routes_climb_id_idx'),
    ('topo_replacement_routes', ARRAY['draft_route_id']::text[], 'topo_replacement_routes_draft_route_id_idx'),
    ('topo_replacements', ARRAY['created_by']::text[], 'topo_replacements_created_by_idx'),
    ('topo_replacements', ARRAY['published_by']::text[], 'topo_replacements_published_by_idx'),
    ('topo_replacements', ARRAY['replacement_image_id']::text[], 'topo_replacements_replacement_image_id_idx'),
    ('topo_route_line_tombstones', ARRAY['climb_id']::text[], 'topo_route_line_tombstones_climb_id_idx'),
    ('topo_route_line_tombstones', ARRAY['deleted_by']::text[], 'topo_route_line_tombstones_deleted_by_idx'),
    ('topo_route_line_tombstones', ARRAY['image_id']::text[], 'topo_route_line_tombstones_image_id_idx'),
    ('topo_route_line_tombstones', ARRAY['replacement_id']::text[], 'topo_route_line_tombstones_replacement_id_idx'),
    ('un_regions', ARRAY['continent_name']::text[], 'un_regions_continent_name_idx'),
    ('user_place_contributor_scores', ARRAY['place_id']::text[], 'user_place_contributor_scores_place_id_idx'),
    ('wiki_entity_revisions', ARRAY['parent_revision_id']::text[], 'wiki_entity_revisions_parent_revision_id_idx'),
    ('wiki_entity_revisions', ARRAY['restored_from_revision_id']::text[], 'wiki_entity_revisions_restored_from_revision_id_idx'),
    ('wiki_entity_revisions', ARRAY['supersedes_revision_id']::text[], 'wiki_entity_revisions_supersedes_revision_id_idx'),
    ('wiki_revision_merge_parents', ARRAY['parent_revision_id']::text[], 'wiki_revision_merge_parents_parent_revision_id_idx'),
    ('crags', ARRAY['last_edited_by']::text[], 'crags_last_edited_by_idx')

) AS planned(table_name, column_names, index_name)
  LOOP
    table_oid := to_regclass(format('public.%I', r.table_name));
    IF table_oid IS NULL THEN RAISE EXCEPTION 'Missing table %', r.table_name; END IF;
    SELECT array_agg(a.attnum ORDER BY k.ord) INTO key_numbers
    FROM unnest(r.column_names) WITH ORDINALITY AS k(name, ord)
    JOIN pg_attribute a ON a.attrelid = table_oid AND a.attname = k.name AND NOT a.attisdropped;
    IF cardinality(key_numbers) IS DISTINCT FROM cardinality(r.column_names) THEN
      RAISE EXCEPTION 'Missing FK columns on %', r.table_name;
    END IF;
    named_oid := to_regclass(format('public.%I', r.index_name));
    IF named_oid IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
      JOIN pg_am am ON am.oid = c.relam
      WHERE i.indexrelid = named_oid AND i.indrelid = table_oid
        AND i.indisvalid AND i.indisready AND i.indpred IS NULL
        AND i.indexprs IS NULL AND am.amname = 'btree'
        AND i.indnkeyatts = cardinality(key_numbers)
        AND (i.indkey::smallint[])[0:cardinality(key_numbers)-1] @> key_numbers
    ) THEN RAISE EXCEPTION 'Conflicting index definition: %', r.index_name; END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
      JOIN pg_am am ON am.oid = c.relam
      WHERE i.indrelid = table_oid AND i.indisvalid AND i.indisready
        AND i.indpred IS NULL AND i.indexprs IS NULL AND am.amname = 'btree'
        AND (i.indkey::smallint[])[0:cardinality(key_numbers)-1] @> key_numbers
    ) THEN
      EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (%s)',
        r.index_name, r.table_name,
        (SELECT string_agg(format('%I', n), ', ') FROM unnest(r.column_names) AS n));
    END IF;
  END LOOP;
END;
$indexes$;

-- Standalone duplicates, not constraint-backed indexes. RESTRICT is intentional.
-- The primary key and username unique constraint retain their enforcement.
DO $duplicates$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('profiles_id_key', 'profiles_pkey', true),
    ('idx_profiles_username', 'profiles_username_key', false)
  ) AS duplicates(redundant, retained, redundant_unique)
  LOOP
    IF to_regclass(format('public.%I', r.redundant)) IS NOT NULL THEN
      IF NOT EXISTS (
        SELECT 1 FROM pg_index a JOIN pg_index b ON b.indrelid = a.indrelid
        JOIN pg_class ac ON ac.oid = a.indexrelid JOIN pg_class bc ON bc.oid = b.indexrelid
        WHERE a.indexrelid = to_regclass(format('public.%I', r.redundant))
          AND b.indexrelid = to_regclass(format('public.%I', r.retained))
          AND a.indrelid = 'public.profiles'::regclass
          AND a.indkey = b.indkey AND a.indclass = b.indclass
          AND a.indcollation = b.indcollation AND a.indoption = b.indoption
          AND ac.relam = bc.relam AND a.indpred IS NULL AND b.indpred IS NULL
          AND a.indexprs IS NULL AND b.indexprs IS NULL
          AND a.indisunique = r.redundant_unique AND b.indisunique
          AND a.indnkeyatts = b.indnkeyatts AND a.indnatts = b.indnatts
          AND NOT a.indisreplident AND NOT a.indisclustered
          AND b.indisvalid AND b.indisready
          AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = a.indexrelid)
      ) THEN RAISE EXCEPTION 'Unsafe duplicate index removal: %', r.redundant; END IF;
      EXECUTE format('DROP INDEX IF EXISTS public.%I RESTRICT', r.redundant);
    END IF;
  END LOOP;
END;
$duplicates$;

-- 3. Equivalent policy cleanup and statement-level identity evaluation.
-- Preserve role lists, permissive/restrictive status, and correlated access checks.
-- Only auth.uid/auth.role/auth.jwt and the STABLE, argument-free admin helper
-- become initplans. Helpers taking a row ID MUST stay correlated.

ALTER POLICY "Authenticated create correction" ON public."climb_corrections"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = user_id)));

ALTER POLICY "Authenticated create verification" ON public."climb_verifications"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = user_id)));

ALTER POLICY "Authenticated delete own verification" ON public."climb_verifications"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner create climb_video_betas" ON public."climb_video_betas"
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner delete climb_video_betas" ON public."climb_video_betas"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner update climb_video_betas" ON public."climb_video_betas"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Admins read all climbs" ON public."climbs"
  USING ((SELECT public.is_current_user_admin()));

ALTER POLICY "Owner create climbs" ON public."climbs"
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner update own pending climbs" ON public."climbs"
  USING ((((SELECT auth.uid()) = user_id) AND ((status)::text = 'pending'::text)))
  WITH CHECK ((((SELECT auth.uid()) = user_id) AND ((status)::text = 'pending'::text)));

ALTER POLICY "Authenticated create comments" ON public."comments"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = author_id) AND (deleted_at IS NULL)));

ALTER POLICY "Author soft delete comments" ON public."comments"
  USING ((((SELECT auth.uid()) = author_id) AND (deleted_at IS NULL)))
  WITH CHECK ((((SELECT auth.uid()) = author_id) AND (deleted_at IS NOT NULL)));

ALTER POLICY "Users manage own place follows" ON public."community_place_follows"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated create own community comments" ON public."community_post_comments"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = author_id)));

ALTER POLICY "Owner delete community comments" ON public."community_post_comments"
  USING (((SELECT auth.uid()) = author_id));

ALTER POLICY "Owner update community comments" ON public."community_post_comments"
  USING (((SELECT auth.uid()) = author_id))
  WITH CHECK (((SELECT auth.uid()) = author_id));

ALTER POLICY "Admins read community rsvps" ON public."community_post_rsvps"
  USING ((SELECT public.is_current_user_admin()));

ALTER POLICY "Users manage own community rsvps" ON public."community_post_rsvps"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated create own community posts" ON public."community_posts"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = author_id)));

ALTER POLICY "Owner delete community posts" ON public."community_posts"
  USING (((SELECT auth.uid()) = author_id));

ALTER POLICY "Owner update community posts" ON public."community_posts"
  USING (((SELECT auth.uid()) = author_id))
  WITH CHECK (((SELECT auth.uid()) = author_id));

ALTER POLICY "Authenticated create correction vote" ON public."correction_votes"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = user_id)));

ALTER POLICY "Authenticated delete own correction vote" ON public."correction_votes"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated create crag_images" ON public."crag_images"
  WITH CHECK (((SELECT auth.role()) = 'authenticated'::text));

ALTER POLICY "Creators link initial crag region" ON public."crag_location_tags"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM crags crag
  WHERE ((crag.id = crag_location_tags.crag_id) AND (crag.created_by = (SELECT auth.uid())) AND (NOT (EXISTS ( SELECT 1
           FROM images
          WHERE (images.crag_id = crag.id)))) AND (NOT (EXISTS ( SELECT 1
           FROM climbs
          WHERE (climbs.crag_id = crag.id)))) AND (NOT (EXISTS ( SELECT 1
           FROM submission_drafts
          WHERE (submission_drafts.crag_id = crag.id)))) AND (NOT (EXISTS ( SELECT 1
           FROM crag_images
          WHERE (crag_images.crag_id = crag.id)))) AND (NOT (EXISTS ( SELECT 1
           FROM wiki_entities
          WHERE (wiki_entities.crag_id = crag.id))))))));

ALTER POLICY "Users read own crag maintainer scopes" ON public."crag_maintainers"
  USING (((user_id = (SELECT auth.uid())) OR (SELECT public.is_current_user_admin())));

ALTER POLICY "Users read own or reviewable crag metadata proposals" ON public."crag_metadata_proposals"
  USING (((proposer_id = (SELECT auth.uid())) OR (SELECT public.is_current_user_admin()) OR (EXISTS ( SELECT 1
   FROM crag_maintainers maintainer
  WHERE ((maintainer.crag_id = crag_metadata_proposals.crag_id) AND (maintainer.user_id = (SELECT auth.uid())))))));

ALTER POLICY "Crag stewards read publication history" ON public."crag_publication_events"
  USING (((SELECT public.is_current_user_admin()) OR (EXISTS ( SELECT 1
   FROM crag_maintainers maintainer
  WHERE ((maintainer.crag_id = crag_publication_events.crag_id) AND (maintainer.user_id = (SELECT auth.uid())))))));

ALTER POLICY "Admins read crag reports" ON public."crag_reports"
  USING ((SELECT public.is_current_user_admin()));

ALTER POLICY "Authenticated create crag report" ON public."crag_reports"
  WITH CHECK ((((SELECT auth.uid()) = reporter_id) AND ((status)::text = 'pending'::text) AND (moderator_id IS NULL) AND (moderator_note IS NULL) AND (resolved_at IS NULL)));

ALTER POLICY "Users read own crag reports" ON public."crag_reports"
  USING (((SELECT auth.uid()) = reporter_id));

ALTER POLICY "Admins read all crags" ON public."crags"
  USING ((SELECT public.is_current_user_admin()));

ALTER POLICY "Authenticated create own crags" ON public."crags"
  WITH CHECK ((created_by = (SELECT auth.uid())));

ALTER POLICY "Crag stewards read active unpublished crags" ON public."crags"
  USING (((deleted_at IS NULL) AND ((created_by = (SELECT auth.uid())) OR (EXISTS ( SELECT 1
   FROM crag_maintainers maintainer
  WHERE ((maintainer.crag_id = crags.id) AND (maintainer.user_id = (SELECT auth.uid()))))))));

ALTER POLICY "Users manage own deletion requests" ON public."deletion_requests"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated create grade vote" ON public."grade_votes"
  WITH CHECK ((user_id = (SELECT auth.uid())));

ALTER POLICY "Authenticated delete own grade vote" ON public."grade_votes"
  USING ((user_id = (SELECT auth.uid())));

ALTER POLICY "Authenticated update own grade vote" ON public."grade_votes"
  USING ((user_id = (SELECT auth.uid())))
  WITH CHECK ((user_id = (SELECT auth.uid())));

ALTER POLICY "Admin write gym_floor_plans" ON public."gym_floor_plans"
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

ALTER POLICY "Admins manage gym memberships" ON public."gym_memberships"
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

ALTER POLICY "Users read own gym memberships" ON public."gym_memberships"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Admin read gym owner applications" ON public."gym_owner_applications"
  USING ((SELECT public.is_current_user_admin()));

ALTER POLICY "Admin update gym owner applications" ON public."gym_owner_applications"
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

ALTER POLICY "Public create gym owner applications" ON public."gym_owner_applications"
  WITH CHECK (((SELECT auth.role()) = ANY (ARRAY['anon'::text, 'authenticated'::text])));

ALTER POLICY "Admin write gym_route_markers" ON public."gym_route_markers"
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

ALTER POLICY "Gym members write gym route markers" ON public."gym_route_markers"
  USING ((EXISTS ( SELECT 1
   FROM (gym_routes gr
     JOIN gym_memberships gm ON ((gm.gym_place_id = gr.gym_place_id)))
  WHERE ((gr.id = gym_route_markers.route_id) AND (gm.user_id = (SELECT auth.uid())) AND (gm.status = 'active'::text) AND (gm.role = ANY (ARRAY['owner'::text, 'manager'::text, 'head_setter'::text, 'setter'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (gym_routes gr
     JOIN gym_memberships gm ON ((gm.gym_place_id = gr.gym_place_id)))
  WHERE ((gr.id = gym_route_markers.route_id) AND (gm.user_id = (SELECT auth.uid())) AND (gm.status = 'active'::text) AND (gm.role = ANY (ARRAY['owner'::text, 'manager'::text, 'head_setter'::text, 'setter'::text]))))));

ALTER POLICY "Admin write gym_routes" ON public."gym_routes"
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

ALTER POLICY "Gym members write gym routes" ON public."gym_routes"
  USING ((EXISTS ( SELECT 1
   FROM gym_memberships gm
  WHERE ((gm.user_id = (SELECT auth.uid())) AND (gm.gym_place_id = gym_routes.gym_place_id) AND (gm.status = 'active'::text) AND (gm.role = ANY (ARRAY['owner'::text, 'manager'::text, 'head_setter'::text, 'setter'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM gym_memberships gm
  WHERE ((gm.user_id = (SELECT auth.uid())) AND (gm.gym_place_id = gym_routes.gym_place_id) AND (gm.status = 'active'::text) AND (gm.role = ANY (ARRAY['owner'::text, 'manager'::text, 'head_setter'::text, 'setter'::text]))))));

ALTER POLICY "Collaborators read shared images" ON public."images"
  USING (is_submission_collaborator(id, (SELECT auth.uid())));

ALTER POLICY "Owner create images" ON public."images"
  WITH CHECK (((SELECT auth.uid()) = created_by));

ALTER POLICY "Owner read own images" ON public."images"
  USING (((SELECT auth.uid()) = created_by));

ALTER POLICY "Authenticated create location tags" ON public."location_tags"
  WITH CHECK (((SELECT auth.role()) = 'authenticated'::text));

ALTER POLICY "Service role manage media_jobs" ON public."media_jobs"
  USING (((SELECT auth.role()) = 'service_role'::text))
  WITH CHECK (((SELECT auth.role()) = 'service_role'::text));

ALTER POLICY "User read own notifications" ON public."notifications"
  USING ((((SELECT auth.uid()) = user_id) OR (SELECT public.is_current_user_admin())));

ALTER POLICY "User update own notifications" ON public."notifications"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated create places" ON public."places"
  WITH CHECK (((SELECT auth.role()) = 'authenticated'::text));

ALTER POLICY "Authenticated create profile" ON public."profiles"
  WITH CHECK (((SELECT auth.uid()) = id));

ALTER POLICY "Owner update profile" ON public."profiles"
  USING ((id = (SELECT auth.uid())))
  WITH CHECK ((id = (SELECT auth.uid())));

ALTER POLICY "Read visible profiles" ON public."profiles"
  USING ((is_public OR (id = (SELECT auth.uid()))));

ALTER POLICY "Authenticated create route grade" ON public."route_grades"
  WITH CHECK ((((SELECT auth.role()) = 'authenticated'::text) AND ((SELECT auth.uid()) = user_id)));

ALTER POLICY "Authenticated delete own route grade" ON public."route_grades"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated update own route grade" ON public."route_grades"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner create route_lines" ON public."route_lines"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM climbs
  WHERE ((climbs.id = route_lines.climb_id) AND (climbs.user_id = (SELECT auth.uid()))))));

ALTER POLICY "Users manage own saved climbs" ON public."saved_climbs"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Users manage own saved crags" ON public."saved_crags"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner create invites" ON public."submission_collaborator_invites"
  WITH CHECK (((EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborator_invites.image_id) AND (i.created_by = (SELECT auth.uid()))))) AND (created_by = (SELECT auth.uid()))));

ALTER POLICY "Owner read invites" ON public."submission_collaborator_invites"
  USING ((EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborator_invites.image_id) AND (i.created_by = (SELECT auth.uid()))))));

ALTER POLICY "Owner revoke invites" ON public."submission_collaborator_invites"
  USING ((EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborator_invites.image_id) AND (i.created_by = (SELECT auth.uid()))))));

ALTER POLICY "Owner add collaborators" ON public."submission_collaborators"
  WITH CHECK (((EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborators.image_id) AND (i.created_by = (SELECT auth.uid()))))) AND (created_by = (SELECT auth.uid()))));

ALTER POLICY "Owner or collaborator read collaborators" ON public."submission_collaborators"
  USING (((user_id = (SELECT auth.uid())) OR (EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborators.image_id) AND (i.created_by = (SELECT auth.uid())))))));

ALTER POLICY "Owner remove collaborators" ON public."submission_collaborators"
  USING ((EXISTS ( SELECT 1
   FROM images i
  WHERE ((i.id = submission_collaborators.image_id) AND (i.created_by = (SELECT auth.uid()))))));

ALTER POLICY "Owner create submission_draft_collaborator_invites" ON public."submission_draft_collaborator_invites"
  WITH CHECK (((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborator_invites.draft_id) AND (d.user_id = (SELECT auth.uid())) AND (d.status = 'draft'::text)))) AND (created_by = (SELECT auth.uid()))));

ALTER POLICY "Owner read submission_draft_collaborator_invites" ON public."submission_draft_collaborator_invites"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborator_invites.draft_id) AND (d.user_id = (SELECT auth.uid()))))));

ALTER POLICY "Owner revoke submission_draft_collaborator_invites" ON public."submission_draft_collaborator_invites"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborator_invites.draft_id) AND (d.user_id = (SELECT auth.uid()))))));

ALTER POLICY "Owner add submission_draft_collaborators" ON public."submission_draft_collaborators"
  WITH CHECK (((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborators.draft_id) AND (d.user_id = (SELECT auth.uid())) AND (d.status = 'draft'::text)))) AND (created_by = (SELECT auth.uid()))));

ALTER POLICY "Owner or collaborator read submission_draft_collaborators" ON public."submission_draft_collaborators"
  USING (((user_id = (SELECT auth.uid())) OR (EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborators.draft_id) AND (d.user_id = (SELECT auth.uid())))))));

ALTER POLICY "Owner or self remove submission_draft_collaborators" ON public."submission_draft_collaborators"
  USING (((user_id = (SELECT auth.uid())) OR (EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_collaborators.draft_id) AND (d.user_id = (SELECT auth.uid())))))));

ALTER POLICY "Users create own or shared submission_draft_images" ON public."submission_draft_images"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_images.draft_id) AND (d.status = 'draft'::text) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))));

ALTER POLICY "Users read own or shared submission_draft_images" ON public."submission_draft_images"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_images.draft_id) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))));

ALTER POLICY "Users update own or shared submission_draft_images" ON public."submission_draft_images"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_images.draft_id) AND (d.status = 'draft'::text) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_images.draft_id) AND (d.status = 'draft'::text) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))));

ALTER POLICY "Users read own or shared submission_draft_routes" ON public."submission_draft_routes"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_routes.draft_id) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))));

ALTER POLICY "Users write own or shared submission_draft_routes" ON public."submission_draft_routes"
  USING ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_routes.draft_id) AND (d.status = 'draft'::text) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM submission_drafts d
  WHERE ((d.id = submission_draft_routes.draft_id) AND (d.status = 'draft'::text) AND ((d.user_id = (SELECT auth.uid())) OR is_submission_draft_collaborator(d.id, (SELECT auth.uid())))))));

ALTER POLICY "Owner or collaborator update draft submission_drafts" ON public."submission_drafts"
  USING (((status = 'draft'::text) AND (((SELECT auth.uid()) = user_id) OR is_submission_draft_collaborator(id, (SELECT auth.uid())))))
  WITH CHECK (((status = 'draft'::text) AND (((SELECT auth.uid()) = user_id) OR is_submission_draft_collaborator(id, (SELECT auth.uid())))));

ALTER POLICY "Users create own submission_drafts" ON public."submission_drafts"
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Users read own or shared submission_drafts" ON public."submission_drafts"
  USING ((((SELECT auth.uid()) = user_id) OR is_submission_draft_collaborator(id, (SELECT auth.uid()))));

ALTER POLICY "Owner create user_climbs" ON public."user_climbs"
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner delete user_climbs" ON public."user_climbs"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner read own user_climbs" ON public."user_climbs"
  USING (((SELECT auth.uid()) = user_id));

ALTER POLICY "Owner update user_climbs" ON public."user_climbs"
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

ALTER POLICY "Authenticated users read visible wiki entities" ON public."wiki_entities"
  USING (((SELECT public.is_current_user_admin()) OR ((image_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM images
  WHERE (images.id = wiki_entities.image_id)))) OR ((climb_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM climbs
  WHERE (climbs.id = wiki_entities.climb_id)))) OR ((crag_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM crags
  WHERE (crags.id = wiki_entities.crag_id)))) OR ((route_line_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM ((route_lines
     JOIN images ON ((images.id = route_lines.image_id)))
     JOIN climbs ON ((climbs.id = route_lines.climb_id)))
  WHERE (route_lines.id = wiki_entities.route_line_id))))));

DROP POLICY IF EXISTS "Users read own place follows" ON public."community_place_follows";

DROP POLICY IF EXISTS "Users can create deletion requests for themselves" ON public."deletion_requests";

DROP POLICY IF EXISTS "Users can update their own deletion requests" ON public."deletion_requests";

DROP POLICY IF EXISTS "Users can view their own deletion requests" ON public."deletion_requests";

DROP POLICY IF EXISTS "Admin read all notifications" ON public."notifications";

DROP POLICY IF EXISTS "Users read own saved climbs" ON public."saved_climbs";

DROP POLICY IF EXISTS "Users read own saved crags" ON public."saved_crags";

-- Admin authorization is profile-bound throughout the application.
-- JWT top-level role is a Postgres role, not the application's is_admin flag.
ALTER POLICY "Admins can manage admin actions" ON public.admin_actions
  TO authenticated
  USING ((SELECT public.is_current_user_admin()))
  WITH CHECK ((SELECT public.is_current_user_admin()));

-- Future private or tombstoned topo lines must not escape via SELECT USING(true).
-- Existing image/climb RLS remains the authority, including owner/collaborator access.
-- Export-owner evaluation is intentionally outside these two API roles.
DROP POLICY IF EXISTS "Route lines require readable parents" ON public.route_lines;
CREATE POLICY "Route lines require readable parents" ON public.route_lines
  AS RESTRICTIVE FOR SELECT TO anon, authenticated
  USING (
    EXISTS (SELECT 1 FROM public.images i WHERE i.id = route_lines.image_id)
    AND EXISTS (SELECT 1 FROM public.climbs c WHERE c.id = route_lines.climb_id)
  );

-- Storage policies differ between production and staging. Optimize only policies
-- actually present, with explicit audited expressions; do not create legacy access.
DO $storage$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
    AND tablename = 'objects' AND policyname = 'Authenticated users can upload') THEN
    ALTER POLICY "Authenticated users can upload" ON storage.objects
      WITH CHECK (bucket_id = 'route-uploads' AND (SELECT auth.role()) = 'authenticated');
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
    AND tablename = 'objects' AND policyname = 'Route uploads read gated') THEN
    ALTER POLICY "Route uploads read gated" ON storage.objects USING (
      bucket_id = 'route-uploads' AND (
        split_part(name, '/', 1) = (SELECT auth.uid())::text OR EXISTS (
          SELECT 1 FROM public.images i WHERE i.storage_bucket = 'route-uploads'
            AND i.storage_path = objects.name
            AND COALESCE(i.moderation_status, 'pending') = 'approved'
        )
      )
    );
  END IF;
END;
$storage$;
ALTER POLICY "Avatar uploads delete own folder" ON storage.objects
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);
ALTER POLICY "Avatar uploads insert own folder" ON storage.objects
  WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);
ALTER POLICY "Avatar uploads read own folder" ON storage.objects
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

-- 4. Referential integrity with content-preserving account deletion.
-- Lock both sides before orphan checks/repair so concurrent user deletion cannot
-- race the migration. These are small tables; locks last until COMMIT.
LOCK TABLE auth.users IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE public.climbs, public.images, public.crags IN SHARE ROW EXCLUSIVE MODE;

-- Four production climbs referenced two nonexistent accounts at audit time.
-- Clear only dangling attribution. IDs, content, geometry, and user logs are retained.
UPDATE public.climbs c SET user_id = NULL
WHERE c.user_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = c.user_id);

DO $attribution$
DECLARE r record; existing pg_constraint%ROWTYPE;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('climbs', 'user_id', 'climbs_user_id_fkey', 'SET NULL', 'n'),
    ('images', 'created_by', 'images_created_by_fkey', 'SET NULL', 'n'),
    ('crags', 'last_edited_by', 'crags_last_edited_by_fkey', 'SET NULL', 'n'),
    ('images', 'last_edited_by', 'images_last_edited_by_fkey', 'SET NULL', 'n'),
    ('submission_collaborators', 'created_by', 'submission_collaborators_created_by_fkey', 'SET NULL', 'n'),
    ('submission_collaborator_invites', 'created_by', 'submission_collaborator_invites_created_by_fkey', 'SET NULL', 'n'),
    ('submission_draft_collaborators', 'created_by', 'submission_draft_collaborators_created_by_fkey', 'SET NULL', 'n'),
    ('submission_draft_collaborator_invites', 'created_by', 'submission_draft_collaborator_invites_created_by_fkey', 'SET NULL', 'n'),
    ('user_climbs', 'user_id', 'user_climbs_user_id_fkey', 'CASCADE', 'c')
  ) AS changes(table_name, column_name, constraint_name, delete_action, delete_code)
  LOOP
    SELECT c.* INTO existing FROM pg_constraint c
    WHERE c.conrelid = to_regclass(format('public.%I', r.table_name))
      AND c.conname = r.constraint_name;
    IF FOUND THEN
      IF existing.contype <> 'f' OR existing.confrelid <> 'auth.users'::regclass
        OR existing.conkey <> ARRAY[(SELECT attnum FROM pg_attribute
          WHERE attrelid = existing.conrelid AND attname = r.column_name)]::smallint[]
        OR existing.confkey <> ARRAY[(SELECT attnum FROM pg_attribute
          WHERE attrelid = 'auth.users'::regclass AND attname = 'id')]::smallint[]
        OR existing.condeferrable OR existing.confupdtype <> 'a'
        OR existing.confmatchtype <> 's' THEN
        RAISE EXCEPTION 'Unexpected FK contract: %', r.constraint_name;
      END IF;
      IF existing.confdeltype::text <> r.delete_code THEN
        EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I RESTRICT',
          r.table_name, r.constraint_name);
      ELSE
        EXECUTE format('ALTER TABLE public.%I VALIDATE CONSTRAINT %I', r.table_name, r.constraint_name);
        CONTINUE;
      END IF;
    END IF;
    EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES auth.users(id) ON DELETE %s NOT VALID',
      r.table_name, r.constraint_name, r.column_name, r.delete_action);
    EXECUTE format('ALTER TABLE public.%I VALIDATE CONSTRAINT %I', r.table_name, r.constraint_name);
  END LOOP;
END;
$attribution$;
-- user_climbs are deleted ONLY when that account is physically deleted; this
-- matches delete_account_atomic's existing explicit log deletion. No logs change now.
-- Retained audit IDs (deleted_accounts/admin_actions) remain deliberate exceptions.

-- 5. Deterministic, single-grouping consensus summaries.
-- The old trigger counted the winning grade only and scanned votes repeatedly.
-- Serialize recomputation on each parent climb; handle OLD and NEW parents if moved.
-- This privileged trigger can write only derived consensus fields and is not an RPC.
CREATE OR REPLACE FUNCTION public.update_climb_consensus_safe()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE target_ids uuid[]; target_id uuid;
BEGIN
  IF TG_OP = 'INSERT' THEN target_ids := ARRAY[NEW.climb_id];
  ELSIF TG_OP = 'DELETE' THEN target_ids := ARRAY[OLD.climb_id];
  ELSE target_ids := ARRAY[OLD.climb_id, NEW.climb_id]; END IF;
  FOR target_id IN SELECT DISTINCT id FROM unnest(target_ids) AS ids(id)
    WHERE id IS NOT NULL ORDER BY id
  LOOP
    PERFORM 1 FROM public.climbs WHERE id = target_id FOR UPDATE;
    IF NOT FOUND THEN CONTINUE; END IF;
    WITH counts AS MATERIALIZED (
      SELECT grade, count(*) AS votes FROM public.grade_votes
      WHERE climb_id = target_id GROUP BY grade
    ), summary AS (
      SELECT COALESCE(sum(votes), 0)::integer AS total,
        (SELECT grade FROM counts ORDER BY votes DESC, grade ASC LIMIT 1) AS winner,
        (SELECT count(*) > 1 FROM counts WHERE votes = (SELECT max(votes) FROM counts)) AS tied
      FROM counts
    )
    UPDATE public.climbs c SET consensus_grade = s.winner,
      total_votes = s.total, grade_tied = s.tied
    FROM summary s WHERE c.id = target_id
      AND ROW(c.consensus_grade, c.total_votes, c.grade_tied)
        IS DISTINCT FROM ROW(s.winner, s.total, s.tied);
  END LOOP;
  RETURN NULL;
END;
$function$;
REVOKE ALL ON FUNCTION public.update_climb_consensus_safe() FROM PUBLIC, anon, authenticated;

-- Repair existing derived data once; on repeat, the DISTINCT guard makes this a no-op.
LOCK TABLE public.grade_votes IN SHARE ROW EXCLUSIVE MODE;
WITH counts AS MATERIALIZED (
  SELECT climb_id, grade, count(*) AS votes FROM public.grade_votes GROUP BY climb_id, grade
), ranked AS (
  SELECT *, row_number() OVER (PARTITION BY climb_id ORDER BY votes DESC, grade ASC) AS position,
    sum(votes) OVER (PARTITION BY climb_id)::integer AS total,
    count(*) OVER (PARTITION BY climb_id, votes) > 1 AS tied
  FROM counts
), summary AS (
  SELECT c.id, r.grade, COALESCE(r.total, 0) AS total, COALESCE(r.tied, false) AS tied
  FROM public.climbs c LEFT JOIN ranked r ON r.climb_id = c.id AND r.position = 1
)
UPDATE public.climbs c SET consensus_grade = s.grade, total_votes = s.total, grade_tied = s.tied
FROM summary s WHERE c.id = s.id
  AND ROW(c.consensus_grade, c.total_votes, c.grade_tied)
    IS DISTINCT FROM ROW(s.grade, s.total, s.tied);

-- Fully qualified invoker functions need no mutable search path. Overloads matter.
ALTER FUNCTION public.get_climbs_with_consensus() SET search_path = '';
ALTER FUNCTION public.get_crag_contributor_leaderboard(uuid, integer, integer) SET search_path = '';
ALTER FUNCTION public.get_place_contributor_leaderboard(uuid, integer, integer) SET search_path = '';

-- Retire a broken runtime-DDL utility: check_definition is not an information_schema
-- column, and its old body replaced the allowed values regardless of its argument.
-- There are no repository callers or API grants. Keep the signature, fail clearly.
CREATE OR REPLACE FUNCTION public.add_correction_type_value(new_value text)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $function$
BEGIN
  RAISE EXCEPTION 'Correction types must be changed by a versioned SQL migration'
    USING ERRCODE = '0A000';
END;
$function$;
REVOKE ALL ON FUNCTION public.add_correction_type_value(text) FROM PUBLIC, anon, authenticated;

-- 6. Timestamp consistency for ordinary mutable records.
-- Preserve explicit timestamps supplied by existing app/RPC code. Do not replace
-- monotonic draft timestamps, client mutation ordering, or immutable wiki timestamps.
CREATE OR REPLACE FUNCTION public.set_record_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $function$
BEGIN
  IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
    AND NEW IS DISTINCT FROM OLD THEN
    NEW.updated_at := statement_timestamp();
  END IF;
  RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION public.set_record_updated_at() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS "community_place_follows_set_updated_at" ON public."community_place_follows";
CREATE TRIGGER "community_place_follows_set_updated_at" BEFORE UPDATE ON public."community_place_follows"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "community_post_comments_set_updated_at" ON public."community_post_comments";
CREATE TRIGGER "community_post_comments_set_updated_at" BEFORE UPDATE ON public."community_post_comments"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "community_posts_set_updated_at" ON public."community_posts";
CREATE TRIGGER "community_posts_set_updated_at" BEFORE UPDATE ON public."community_posts"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "gym_floor_plans_set_updated_at" ON public."gym_floor_plans";
CREATE TRIGGER "gym_floor_plans_set_updated_at" BEFORE UPDATE ON public."gym_floor_plans"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "gym_memberships_set_updated_at" ON public."gym_memberships";
CREATE TRIGGER "gym_memberships_set_updated_at" BEFORE UPDATE ON public."gym_memberships"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "gym_owner_applications_set_updated_at" ON public."gym_owner_applications";
CREATE TRIGGER "gym_owner_applications_set_updated_at" BEFORE UPDATE ON public."gym_owner_applications"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "gym_route_markers_set_updated_at" ON public."gym_route_markers";
CREATE TRIGGER "gym_route_markers_set_updated_at" BEFORE UPDATE ON public."gym_route_markers"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "gym_routes_set_updated_at" ON public."gym_routes";
CREATE TRIGGER "gym_routes_set_updated_at" BEFORE UPDATE ON public."gym_routes"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "location_tags_set_updated_at" ON public."location_tags";
CREATE TRIGGER "location_tags_set_updated_at" BEFORE UPDATE ON public."location_tags"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

DROP TRIGGER IF EXISTS "profiles_set_updated_at" ON public."profiles";
CREATE TRIGGER "profiles_set_updated_at" BEFORE UPDATE ON public."profiles"
  FOR EACH ROW EXECUTE FUNCTION public.set_record_updated_at();

-- All existing base-table created_at/updated_at defaults are already now()/timestamptz.
-- No speculative NOT NULL changes, geography conversions, or JSON flattening.
-- Full local type generation in CI confirmed types/database.ts is unchanged.
NOTIFY pgrst, 'reload schema';
COMMIT;
