-- Migration: Fix desynced image UUIDs
-- Problem: images.id auto-generated by PostgreSQL, but images.url contains
-- the upload session UUID in the path (images/originals/{uuid}/original.jpg).
-- The CDN/proxy uses the URL UUID to locate the R2 object, so when
-- images.id != UUID in the URL, images fail to load.
--
-- Fix: Update images.id to match the UUID in images.url for all desynced rows.
-- FK references in child tables are updated first to avoid constraint violations.
-- For rows where the target UUID already exists (upload session created it),
-- we merge: move FK references to the existing row and delete the orphan.

DO $$
BEGIN
  -- 1. Build mapping: wrong_id → correct_id (extracted from URL)
  CREATE TEMP TABLE _image_uuid_fix AS
  SELECT
    id AS wrong_id,
    (regexp_match(url, 'images/originals/([0-9a-fA-F-]{36})'))[1]::uuid AS correct_id
  FROM public.images
  WHERE url LIKE '%images/originals/%'
    AND (regexp_match(url, 'images/originals/([0-9a-fA-F-]{36})'))[1] IS NOT NULL
    AND id != (regexp_match(url, 'images/originals/([0-9a-fA-F-]{36})'))[1]::uuid;

  RAISE NOTICE 'Found % desynced image(s) to fix', (SELECT count(*) FROM _image_uuid_fix);

  IF EXISTS (SELECT 1 FROM _image_uuid_fix) THEN
    -- 2. Update FK references in child tables (safe regardless of whether correct_id exists)
    UPDATE public.route_lines rl
    SET image_id = m.correct_id
    FROM _image_uuid_fix m
    WHERE rl.image_id = m.wrong_id;

    UPDATE public.crag_images ci
    SET linked_image_id = m.correct_id
    FROM _image_uuid_fix m
    WHERE ci.linked_image_id = m.wrong_id;

    UPDATE public.crag_images ci
    SET source_image_id = m.correct_id
    FROM _image_uuid_fix m
    WHERE ci.source_image_id = m.wrong_id;

    UPDATE public.climb_flags cf
    SET image_id = m.correct_id
    FROM _image_uuid_fix m
    WHERE cf.image_id = m.wrong_id;

    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'submission_draft_images' AND column_name = 'image_id'
    ) THEN
      UPDATE public.submission_draft_images sdi
      SET image_id = m.correct_id
      FROM _image_uuid_fix m
      WHERE sdi.image_id = m.wrong_id;
    END IF;

    -- 3. Update images.id where correct_id doesn't already exist (avoids PK conflict)
    UPDATE public.images
    SET id = m.correct_id
    FROM _image_uuid_fix m
    LEFT JOIN public.images existing ON existing.id = m.correct_id
    WHERE images.id = m.wrong_id
      AND existing.id IS NULL;

    -- 4. Delete orphaned rows that couldn't be updated (correct_id already existed)
    DELETE FROM public.images
    WHERE id IN (SELECT wrong_id FROM _image_uuid_fix);
  END IF;

  DROP TABLE IF EXISTS _image_uuid_fix;
END;
$$;
